name: Publish to GitHub Pages

env:
  HUGO_VERSION: "0.79.1"

on:
  push:
    branches:
      - master
      

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_publish:
    name: Generate and publish website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install pipenv
        run: |
           python -m pip install --upgrade pip
           pip install pipenv
      - name: Cache bib2md dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-bib2md-dependencies
        with:
          path: ~/.local/share/virtualenvs/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('Pipfile.lock') }}
      - name: Install bib2md dependencies
        run: |
           pipenv install
      - name: Generate publications
        run: |
          make publications
      - name: Cache hugo
        uses: actions/cache@v2
        env:
          cache-name: cache-hugo-${{ env.HUGO_VERSION }}
        with:
          path: hugo
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
      - name: Install hugo
        run:
          wget -q https://github.com/gohugoio/hugo/releases/download/v${{ env.HUGO_VERSION }}/hugo_${{ env.HUGO_VERSION }}_Linux-64bit.tar.gz -O - | tar xz hugo

      - name: Prepare worktree
        run:
          git worktree add --track -b gh-pages public origin/gh-pages

      - name: Clear generated publications directory in case of deletions
        run:
          find public/publications -mindepth 1 -delete || true

      - name: Generate website
        run:
          make generate

      - name: Publish public
        run: |
          cd public
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          (git add --all . && git commit -m "Publish changes" -a && git push origin gh-pages) || true
