baseURL: "/"
canonifyURLs: true

languageCode: "en"
DefaultContentLanguage: "en"
title: "Website of Jane Doe"
theme: "anatole"
summarylength: 10
enableEmoji: true
enableRobotsTXT: true
enableGitInfo: true
disableKinds:
  - RSS
disableHugoGeneratorInject: true
metaDataFormat: "yaml"
publishDir: "public"
pygmentsCodeFences: true
pygmentsUseClasses: true
pygmentsOptions: "linenos=table"
taxonomies: []

sitemap:
 changefreq: weekly

params:
  title: Noah Spahn
  author: ncs
  description: Software Engineer
  profilePicture: images/ncs.png
  contentratio: 0.8

menu:
  main:
    - name: Home
      identifier: home
      weight: 100
      url: /
    - name: Publications
      weight: 200
      identifier: publications
      url: /publications/
    - name: Teaching
      weight: 300
      identifier: teaching
      url: /teaching/
